# configs/pose.yaml
defaults:
  - _self_

n: 100000
concentration_top: 1E6
concentration_side: 1E6
prob_top: 0.0
prob_side: 1.0
euler_convention: ZYZ
output_path: nonuniform_pose.star

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
