# configs/pose.yaml
defaults:
  - _self_

n: 1
concentration_top: 0.0
concentration_side: 0.0
prob_top: 0.5
prob_side: 0.5
euler_convention: ZXZ
output_path: nonuniform_pose.star

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}